
title: Resume | Tsung Wu
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
description: "Tsung-Ting, Wu's online CV'"
keyword: "Tsung Wu, Guitar, Recording, Music, 吳宗庭, Tsung-Ting Wu"

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

# Google Analytics
ga_track_id: 'UA-98280725-1'            # Format: UA-xxxxxx-xx
ga_domain: 'tsungtwu.github.io'


#Profile information
name: Tsung-Ting Wu
tagline:  Full Stack Web Developer </br> DevOps Engineer </br> Sound Engineer </br> Guitarist
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: jtrmn.wu@gmail.com
#phone: 012 345 6789
#website: tsungtwu.github.io #do not add http://
#linkedin: 
github: tsungtwu
#twitter: '@webjeda'
facebook: jtrmn.wu
youtube: jtrmnW
soundcloud: jtrmn
medium: '@tsung.wu'
#Update all the sections by editing the files inside _includes folder.
